trigger:
  batch: true
  branches:
    include:
      - main

pr:
  - main

schedules:
  - cron: "0 20 * * *"
    displayName: Daily midnight build
    branches:
      include:
        - main
    always: "true"

resources:
  repositories:
    - repository: cnp-azuredevops-libraries
      type: github
      ref: refs/heads/master
      name: hmcts/cnp-azuredevops-libraries
      endpoint: 'hmcts'

parameters:
  - name: overrideAction
    type: string
    default: plan
    values:
      - plan
      - apply
      - destroy
  - name: environment_components
    type: object
    default:
      - deployment: 'stg_core'
        environment: 'stg'
        component: 'core'
        service_connection: 'DTS-HERITAGE-INTSVC-STG'
        dependsOn: 'Precheck'
      - deployment: 'stg_backend_database'
        environment: 'stg'
        component: 'database'
        service_connection: 'DTS-HERITAGE-INTSVC-STG'
        dependsOn: 'stg_core'
      - deployment: 'stg_vm'
        environment: 'stg'
        component: 'vm'
        service_connection: 'DTS-HERITAGE-INTSVC-STG'
        dependsOn: 'stg_core'
      #- deployment: 'stg_appgw'
      #  environment: 'stg'
      #  component: 'app-gateway'
      #  service_connection: 'DTS-HERITAGE-INTSVC-STG'
      #  dependsOn: 'stg_vm'
      - deployment: 'stg_rbac'
        environment: 'stg'
        component: 'rbac'
        service_connection: 'ops-approval-gate-stg-envs'
        dependsOn: 'stg_vm'
      - deployment: 'prod_core'
        environment: 'prod'
        component: 'core'
        service_connection: 'DTS-HERITAGE-INTSVC-PROD'
        dependsOn: 
          #- 'stg_appgw'
          - 'stg_rbac'
          - 'stg_backend_database'
      - deployment: 'prod_backend_database'
        environment: 'prod'
        component: 'database'
        service_connection: 'DTS-HERITAGE-INTSVC-PROD'
        dependsOn: 
          - 'prod_core'
      - deployment: 'prod_vm'
        environment: 'prod'
        component: 'vm'
        service_connection: 'DTS-HERITAGE-INTSVC-PROD'
        dependsOn:
          - 'prod_core'
      - deployment: 'prod_appgw'
        environment: 'prod'
        component: 'app-gateway'
        service_connection: 'DTS-HERITAGE-INTSVC-PROD'
        dependsOn: 'prod_vm'
      - deployment: 'prod_rbac'
        environment: 'prod'
        component: 'rbac'
        service_connection: 'ops-approval-gate-prod-envs'
        dependsOn: 'prod_vm'

variables:
  - name: timeoutInMinutes
    value: 60
  - name: agentImage
    value: ubuntu-20.04
  - name: product
    value: crime-portal
  - name: terraformInitSubscription
    value: 04d27a32-7a07-48b3-95b8-3c8691e1a263
  - template: vars/input-variables.yaml@cnp-azuredevops-libraries

stages:
  - stage: Precheck
    jobs:
      - job: TerraformPrecheck
        pool:
          vmImage: ${{ variables.agentImage }}
        steps:
          - template: steps/terraform-precheck.yaml@cnp-azuredevops-libraries
            parameters:
              keyvaultName: 'infra-vault-nonprod'
              keyvaultSecret: 'azure-devops-sp-token'
              serviceConnection: 'azurerm-sandbox'
              overrideAction: ${{ parameters.overrideAction }}

  - ${{ each deployment in parameters.environment_components }}:
    - stage: ${{ deployment.deployment }}
      dependsOn: ${{ deployment.dependsOn }}
      jobs:
        - job: TerraformPlanApply
          pool: hmcts-sds-ptl
          timeoutInMinutes: ${{ variables.timeoutInMinutes }}
          steps:
            - template: steps/terraform.yaml@cnp-azuredevops-libraries
              parameters:
                overrideAction: ${{ parameters.overrideAction }}
                environment: ${{ deployment.environment }}
                component: ${{ deployment.component }}
                serviceConnection: ${{ deployment.service_connection }}
                terraformInitSubscription: ${{ variables.terraformInitSubscription }}
                product: ${{ variables.product }}
                planCommandOptions:
                  -compact-warnings

